name: Publish STAC JSON schema
on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create github release
        if: startsWith(github.ref, 'refs/tags/v')
        run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: sed -i "s/_STAC_VERSION_/$GITHUB_REF/" extensions/**/*.*
        if: startsWith(github.ref, 'refs/tags/v')
        
      - name: Deploy JSON Schema for version ${{ env.GITHUB_REF }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: extensions
          destination_dir: ${{ env.GITHUB_REF }}

