name: Publish STAC JSON schema
on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Create github release
        run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Version schema
        run: yarn run version-schema

      - name: Prepare tag
        id: git
        run: echo "::set-output name=tag::${GITHUB_REF##*/}"

      - name: Deploy JSON Schema for version ${{ env.GITHUB_REF }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: extensions
          enable_jekyll: true
          destination_dir: ${{ steps.git.outputs.tag }}
