name: Publish STAC JSON schema
on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Create github release
        run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Version schema
        run: yarn run version-schema

      - name: Prepare tag
        id: git
        run: echo "::set-output name=tag::${GITHUB_REF##*/}"

      - name: Deploy JSON Schema for version ${{ env.GITHUB_REF }}
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: extensions
          enable_jekyll: true
          destination_dir: ${{ steps.git.outputs.tag }}
