name: Test
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm test
