name: Test
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: linz/action-typescript@v1
      - run: yarn validate

      - name: Create github release
        if: startsWith(github.ref, 'refs/tags/v')
        run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
