name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: linz/action-typescript@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - name: Deploy docs
        run: |
          aws s3 cp package.json s3://${BUCKET_NAME}/
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
