name: Test
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - run: npm install yarn
      - run: yarn
      - uses: actions/setup-python@v2.2.2
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pre-commit run --all-files
