name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: linz/action-typescript@v1
      - name: Verify that there are no unknown ospec stderr lines
        run: '! (npx ospec 3>&2 2>&1 1>&3-) 2>/dev/null | grep --fixed-strings --invert-match --regex=stac-extensions.github.io --regex=schemas.stacspec.org'

  build-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: linz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-shell --pure --run true
