name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: linz/action-typescript@v1
      - run: yarn validate

      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
