name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: linz/action-typescript@v1
      - run: yarn validate

  build-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: linz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-shell --pure --run true
